[build]
  base = "projects/active/ai-github-interface"
  publish = "frontend"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200