[build]
  # Base directory is set in Netlify UI as: projects/active/ai-github-interface/frontend
  # So we don't override it here
  publish = "."  # Current directory since base is already frontend
  functions = "../netlify/functions"  # Go up from frontend, then into netlify/functions
  command = ""

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# IMPORTANT: More specific redirects must come FIRST
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
