[build]
  base = "projects/active/ai-github-interface"
  publish = "frontend"
  functions = "netlify/functions"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200