[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd projects/active/ai-github-interface/backend && npm ci"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd projects/active/ai-github-interface/backend && npm start"