name = "ai-github-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
MCP_SERVER_URL = "https://github-mcp-remote.metamike.workers.dev"

# Add your GitHub PAT as a secret:
# wrangler secret put GITHUB_TOKEN